version: '3.1'
services:
  verifier:
    build:
      context: .
    env_file: .env
    image: trace4eu-verifier:latest
    container_name: trace4eu-verifier
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    container_name: redis-verifier
    image: redis
    ports:
      - "6379:6379"
