name: Test the Authorization Server

on:
  workflow_dispatch:

jobs:
  test-authorization-server:
    name: Test the Authorization Server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: packages/authorization-server
        run: |
          npm install

      - name: Run Authorization Server Tests
        working-directory: packages/authorization-server
        run: |
          npm run test:e2e
        continue-on-error: true

      - name: Generate Allure Report using action
        if: always()
        uses: simple-elf/allure-report-action@v1.12 
        with:
          allure_results: allure-results
          gh_pages: allure-report 
      
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
          retention-days: 30  