name: Test the Verifier

on:
  workflow_dispatch:
    inputs:
      test-type:
        type: choice
        description: Test type
        required: true
        default: e2e
        options:
          - e2e
          - integration
          - unit

jobs:
  test-verifier:
    name: Test the Verifier
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Wait for Redis to be ready
        run: |
          for i in {1..10}; do
            if echo PING | nc localhost 6379 | grep PONG; then
              echo "Redis is ready"
              break
            fi
            sleep 5
          done

      - name: Set up env variables
        run: |
          echo "${{ secrets.SECRETS_BASE64 }}" | base64 --decode > packages/verifier/.env
          echo "REDIS_HOST=localhost" >> packages/verifier/.env
          echo "REDIS_PORT=6379" >> packages/verifier/.env

      - name: Install dependencies
        working-directory: packages/verifier
        run: |
          npm install

      - name: Run Verifier Tests
        working-directory: packages/verifier
        run: |
          npm run test:${{ github.event.inputs.test-type || 'e2e' }}
        continue-on-error: true