name: Test the Verifier

on:
  workflow_dispatch:
    inputs:
      test-type:
        type: choice
        description: Test type
        required: true
        default: e2e
        options:
          - e2e
          - integration
          - unit

jobs:
  test-verifier:
    name: Test the Verifier
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-server --test-memory 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Debugging Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y iputils-ping dnsutils redis-tools curl

      - name: Debug Redis Connectivity
        run: |
          echo "Checking Redis connection via 'redis-cli':"
          redis-cli -h redis -p 6379 PING || echo "Redis connection failed"
          echo "Checking Redis logs for errors:"
          docker ps | grep redis
          docker logs $(docker ps | grep redis | awk '{print $1}')

      - name: Network Debugging
        run: |
          echo "Checking networking:"
          hostname
          cat /etc/hosts
          echo "Docker Container List:"
          docker ps
          echo "Redis logs:"
          docker logs $(docker ps | grep redis | awk '{print $1}')

      - name: Wait for Redis to be ready
        run: |
          for i in {1..20}; do
            if redis-cli -h redis -p 6379 PING | grep -q PONG; then
              echo "Redis is ready."
              exit 0
            fi
            echo "Waiting for Redis to become ready..."
            sleep 5
          done
          echo "Redis is not ready after retries."
          exit 1

      - name: Set up Environment Variables
        run: |
          echo "${{ secrets.SECRETS_BASE64 }}" | base64 --decode > packages/verifier/.env
          echo "REDIS_HOST=redis" >> packages/verifier/.env
          echo "REDIS_PORT=6379" >> packages/verifier/.env

      - name: Install Dependencies
        working-directory: packages/verifier
        run: npm install

      - name: Run Verifier Tests
        working-directory: packages/verifier
        run: npm run test:${{ github.event.inputs.test-type || 'e2e' }}